"""P6 probe: the checker prototype end to end on relation-schema files (P2's C1 schema language).

Run (from the repository root or anywhere):
    PYTHONPATH=<repo>/src python probe_schemas.py            (writes out/probe_schemas.json and out/hg/*.hg)
    P6_TOOLS=<builds dir> PYTHONPATH=<repo>/src python probe_schemas.py    (also cross-checks with BalancedGo)

For each schema: load_schema (layers J, V, M) -> schema_hypergraph(slots) -> classify + widths (p6check) ->
compare the GYO residue with khg_contracts.schema.is_alpha_acyclic -> write the HyperBench file with safe names
(R<i> for relations, V<j> for roles, plus a mapping) -> optionally run BalancedGo -exact -det on it.
"""
from __future__ import annotations

import glob
import json
import os
import subprocess
import sys

from khg_contracts import data
from khg_contracts.schema import is_alpha_acyclic, load_schema, schema_hypergraph

import p6check as pc

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))

PACKAGED = ["fixture/fixture.relation-schema.json", "fixture/cyclic.relation-schema.json",
            "fixture/wikidata-shaped.relation-schema.json", "sample/sample.relation-schema.json"]


def to_hyperbench(hg: dict) -> tuple[str, dict]:
    """HyperBench text with collision-free ASCII names; returns (text, mapping)."""
    roles = {r: f"V{i}" for i, r in enumerate(hg["vertices"])}
    rels = {r: f"R{i}" for i, r in enumerate(hg["hyperedges"])}
    lines = [f"{rels[r]} ({', '.join(roles[v] for v in vs)})" for r, vs in hg["hyperedges"].items()]
    text = "% generated by probe_schemas.py\n" + ",\n".join(lines) + ".\n"
    return text, {"relations": rels, "roles": roles}


def main() -> None:
    files = [("packaged:" + p, data.path(p)) for p in PACKAGED]
    files += [("constructed:" + os.path.basename(p), p) for p in sorted(glob.glob(os.path.join(HERE, "schemas", "*.relation-schema.json")))]
    out = {}
    os.makedirs(os.path.join(HERE, "out", "hg"), exist_ok=True)
    tools = os.environ.get("P6_TOOLS")
    for label, path in files:
        s = load_schema(path)
        for slots in [("core", "qualifier"), ("core", "qualifier", "time")]:
            hg = schema_hypergraph(s, slots=slots)
            key = f"{label} [{'+'.join(slots)}]"
            if not hg["hyperedges"]:
                out[key] = {"empty": True}
                continue
            rep = pc.report(hg["hyperedges"], limit=18, kmax=5)
            acyclic, residue = is_alpha_acyclic(hg)
            rep["khg_contracts_gyo"] = {"acyclic": acyclic, "residue": residue}
            assert acyclic == rep["alpha"], key
            assert acyclic or sorted(map(sorted, residue)) == sorted(map(sorted, rep["gyo_residue"])), key
            text, mapping = to_hyperbench(hg)
            stem = os.path.basename(path).replace(".relation-schema.json", "") + "." + "-".join(slots)
            hgfile = os.path.join(HERE, "out", "hg", stem + ".hg")
            open(hgfile, "w").write(text)
            json.dump(mapping, open(os.path.join(HERE, "out", "hg", stem + ".map.json"), "w"), indent=1)
            if tools:
                r = subprocess.run([os.path.join(tools, "BalancedGo", "BalancedGo"), "-graph", hgfile, "-exact", "-det"],
                                   capture_output=True, text=True, timeout=300)
                w = [ln.split()[1] for ln in r.stdout.splitlines() if ln.startswith("Width:")]
                rep["balancedgo_hw"] = int(w[0]) if w and "Correct:  true" in r.stdout else r.stdout[-300:]
            rep.pop("hd", None)
            out[key] = rep
            print(key, {k: rep[k] for k in ("class", "vertices", "edges", "core", "tw_primal", "ghw", "fhw", "hw") if k in rep},
                  "balancedgo_hw=" + str(rep.get("balancedgo_hw", "-")), flush=True)
    json.dump(out, open(os.path.join(HERE, "out", "probe_schemas.json"), "w"), indent=1, default=str)


if __name__ == "__main__":
    main()
