"""W4: ``validate/engines.py``: both engines offline with closed resolvers, and the codes they name (DESIGN §8.1).

- Every packaged schema compiles under both engines with sockets blocked (``tests/conftest.py`` blocks them).
- A ``$ref`` to anything that is not packaged fails closed, whatever its scheme.
- Every constraint of our schemas carries an ``x-khg-code`` that names a registered, active code of its layer.
- The H table covers the vendored HIF schema, which carries no annotations.
"""
from __future__ import annotations

import copy
import socket

import pytest

from khg_contracts import data
from khg_contracts.schema.codegen import CHILD_LIST, CHILD_MAPS, CHILD_ONE, CONSTRAINT_KEYS
from khg_contracts.validate import engines, registry

ENGINES = engines.ENGINES
ROOTS = sorted(data.schema_documents())
OURS = [sid for sid in ROOTS if sid != engines.HIF_SCHEMA_ID]
#: The queue schema (W9), packaged in ``data/schemas`` and generated by ``khg_contracts.queue.codegen``.
QUEUE_SCHEMA_ID = engines.TAG + "khg-queue/1.0.0"
#: The layer of the codes each of our schemas names (the C5 output schema reuses C010).
LAYER_OF_SCHEMA = {engines.RECORD_SCHEMA_ID: {"C"}, engines.RELATION_SCHEMA_ID: {"M"},
                   engines.PROFILE_SCHEMA_ID: {"P"}, engines.C4_SCHEMA_ID: {"I"}, engines.C5_SCHEMA_ID: {"C"},
                   QUEUE_SCHEMA_ID: {"Q"}}


def test_sockets_are_blocked_in_these_tests():
    with pytest.raises(OSError):
        socket.create_connection(("json-schema.org", 80), timeout=1)


def test_the_seven_packaged_schemas_are_served():
    assert ROOTS == sorted([engines.HIF_SCHEMA_ID, engines.RECORD_SCHEMA_ID, engines.RELATION_SCHEMA_ID,
                            engines.PROFILE_SCHEMA_ID, engines.C4_SCHEMA_ID, engines.C5_SCHEMA_ID, QUEUE_SCHEMA_ID])
    docs = engines.schema_documents()
    assert docs == data.schema_documents()
    docs[engines.RECORD_SCHEMA_ID]["title"] = "changed"  # a copy: the engines' documents do not change
    assert engines.schema_documents()[engines.RECORD_SCHEMA_ID]["title"] != "changed"


#: What each packaged schema accepts (§1.4), and the layer of what it reports on an empty object.
GOOD = {
    engines.HIF_SCHEMA_ID: ["fixture/fixture.hif.json", "fixture/fixture.directed-slice.hif.json",
                            "sample/sample.khg.hif.json"] + [f"role-convention/{n}.hif.json" for n in
                                                             ("basic", "ordered", "tail-head", "two-roles",
                                                              "undirected")],
    engines.PROFILE_SCHEMA_ID: ["fixture/fixture.hif.json", "fixture/fixture.directed-slice.hif.json",
                                "sample/sample.khg.hif.json"],
    engines.RECORD_SCHEMA_ID: ["fixture/fixture.c1.json", "fixture/fixture.history.c1.json",
                               "fixture/fixture.with-derived.c1.json", "fixture/smoke-base.c1.json",
                               "sample/sample.khg.json"],
    engines.RELATION_SCHEMA_ID: ["fixture/fixture.relation-schema.json", "fixture/cyclic.relation-schema.json",
                                 "fixture/wikidata-shaped.relation-schema.json", "sample/sample.relation-schema.json"],
    engines.C4_SCHEMA_ID: ["fixture/c4-items.jsonl"],
    engines.C5_SCHEMA_ID: ["fixture/c5-outputs.jsonl"],
    QUEUE_SCHEMA_ID: ["fixture/smoke-queue.khg-queue.jsonl"],
}
EMPTY_LAYER = {engines.HIF_SCHEMA_ID: "H", engines.PROFILE_SCHEMA_ID: "H", engines.RECORD_SCHEMA_ID: "C",
               engines.RELATION_SCHEMA_ID: "M", engines.C4_SCHEMA_ID: "I", engines.C5_SCHEMA_ID: "C",
               QUEUE_SCHEMA_ID: "Q"}


@pytest.mark.parametrize("engine", ENGINES)
@pytest.mark.parametrize("root", ROOTS)
def test_every_packaged_schema_compiles_offline_and_accepts_the_packaged_files(root, engine):
    runner = engines.compile_schema(root, engine=engine)
    assert runner is engines.compile_schema(root, engine=engine)  # cached
    for rel in GOOD[root]:
        instances = data.load_jsonl(rel) if rel.endswith(".jsonl") else [data.load_json(rel)]
        assert [runner(x) for x in instances] == [[] for _ in instances], rel
    empty = runner({})
    assert empty and empty[0]["layer"] == EMPTY_LAYER[root]
    assert all(f["code"] in registry() for f in empty)


@pytest.mark.parametrize("engine", ENGINES)
def test_the_jsonl_lines_of_a_container_pass_the_header_and_record_definitions(engine):
    header, *records = data.load_jsonl("fixture/fixture.c1.jsonl")
    assert engines.findings(engines.RECORD_SCHEMA_ID, header, fragment="/definitions/header", engine=engine) == []
    for r in records:
        assert engines.findings(engines.RECORD_SCHEMA_ID, r, fragment="/definitions/record", engine=engine) == []


_FIXTURE = data.load_json("fixture/fixture.c1.json")["records"]
_KING14 = next(r for r in _FIXTURE if r["id"] == "f:king-14")
_TP53 = next(r for r in _FIXTURE if r["id"] == "ex:TP53")


@pytest.mark.parametrize("engine", ENGINES)
@pytest.mark.parametrize(("fragment", "good", "bad", "code"), [
    ("/definitions/record", _TP53, {"kind": "claim"}, "KHG-C002"),
    ("/definitions/hyperedge", _KING14, dict(_KING14, arity=3), "KHG-C009"),
    ("/definitions/entity", _TP53, dict(_TP53, id="ex: TP53"), "KHG-C011"),
    ("/definitions/value", {"special": "somevalue"}, {"entity": "ex:a", "fact": "f:b"}, "KHG-C001"),
    ("/definitions/literal", {"datatype": "quantity", "amount": "+3.5", "unit": "1"},
     {"datatype": "quantity", "amount": 3.5, "unit": "1"}, "KHG-C011"),
])
def test_record_fragments_compile_offline(fragment, good, bad, code, engine):
    runner = engines.compile_schema(engines.RECORD_SCHEMA_ID, fragment, engine=engine)
    assert runner(good) == []
    assert code in [f["code"] for f in runner(bad)]


@pytest.mark.parametrize("engine", ENGINES)
@pytest.mark.parametrize("uri", ["https://example.org/schema.json", "http://json-schema.org/draft-07/schema#",
                                 "file:///etc/hosts", "urn:example:schema", "ftp://example.org/s.json",
                                 "tag:khg-contracts,2026:schema/khg-record/9.9.9",
                                 "tag:khg-contracts,2026:schema/khg-record/1.0.0#/definitions/nowhere"])
def test_a_ref_to_anything_not_packaged_fails_closed(uri, engine):
    base, _, fragment = uri.partition("#")
    with pytest.raises(engines.Unresolvable):
        engines.compile_schema(base, fragment, engine=engine)


def test_the_fastjsonschema_handler_map_answers_every_scheme():
    handlers = engines._ClosedHandlers()
    for scheme in ("http", "https", "tag", "file", "ftp", "urn", "data", ""):
        assert scheme in handlers
        with pytest.raises(engines.Unresolvable):
            handlers[scheme](f"{scheme}://example.org/x.json")
    assert handlers["tag"](engines.RECORD_SCHEMA_ID)["$id"] == engines.RECORD_SCHEMA_ID


def test_relative_refs_cannot_leave_their_document():
    assert engines._absolute("#/definitions/x", "tag:a,2026:b") == "tag:a,2026:b#/definitions/x"
    assert engines._absolute("https://x.org/y", "tag:a,2026:b") == "https://x.org/y"
    with pytest.raises(engines.Unresolvable):
        engines._absolute("other.json#/x", "tag:a,2026:b")


def test_every_packaged_ref_is_reachable_and_absolute():
    for sid in OURS:
        uris = engines._reachable(sid)
        assert uris[0] == sid and all(":" in u.split("#")[0] for u in uris)
    refs = list(engines.refs(data.schema_documents()[engines.C4_SCHEMA_ID]))
    assert refs and all(r.startswith(engines.RECORD_SCHEMA_ID + "#/definitions/") for r in refs)
    assert list(engines.refs(data.hif_schema())) == []


def _subschemas(s, path=""):
    """Every subschema of a schema document (the positions the generator propagates codes to)."""
    if not isinstance(s, dict):
        return
    yield path, s
    for k in CHILD_MAPS:
        for name, v in (s.get(k) or {}).items():
            yield from _subschemas(v, f"{path}/{k}/{name}")
    for k in CHILD_ONE:
        if isinstance(s.get(k), dict):
            yield from _subschemas(s[k], f"{path}/{k}")
    for k in CHILD_LIST:
        for i, v in enumerate(s.get(k) or []):
            yield from _subschemas(v, f"{path}/{k}/{i}")
    for name, v in (s.get("dependencies") or {}).items():
        yield from _subschemas(v, f"{path}/dependencies/{name}")


def _failing_keywords(sub):
    """The keywords of a subschema that fail as themselves (a schema-valued additionalProperties,
    propertyNames or dependency fails through its own subschema)."""
    for keyword in sorted(CONSTRAINT_KEYS & set(sub)):
        value = sub[keyword]
        if keyword == "propertyNames" or keyword == "additionalProperties" and isinstance(value, dict):
            continue
        if keyword == "dependencies" and all(isinstance(v, dict) for v in value.values()):
            continue
        yield keyword


@pytest.mark.parametrize("sid", OURS)
def test_every_constraint_names_a_registered_active_code_of_its_layer(sid):
    """The coverage test of §8.1: the generator propagated a code to every constraint-bearing subschema."""
    reg = registry()
    doc = data.schema_documents()[sid]
    seen, checked = set(), 0
    for path, sub in _subschemas(doc):
        for keyword in _failing_keywords(sub):
            checked += 1
            code = engines.code_of(sub, keyword)
            assert code is not None, f"{sid}{path}: {keyword} has no x-khg-code"
            assert code in reg and reg[code].active, (sid, path, keyword, code)
            seen.add(code)
    assert checked > 20
    assert {reg[c].layer for c in seen} == LAYER_OF_SCHEMA[sid]


#: The disjunctions of the C4 draft (W11a): an instant or null, and a put or an apply event. They carry I002.
C4_DISJUNCTIONS = ["/allOf/3/then/properties/where/properties/as_of", "/allOf/4/then/properties/events/items",
                   "/allOf/5/then/allOf/0/properties/where/properties/as_of"]


@pytest.mark.parametrize("sid", OURS)
def test_if_then_dispatch_replaces_one_of_and_any_of(sid):
    """No oneOf or anyOf outside a ``not`` (a negated disjunction fails as ``not``), except in the C4 draft,
    whose three disjunctions carry their own code."""
    doc = data.schema_documents()[sid]
    found = [p for p, sub in _subschemas(doc) if ("oneOf" in sub or "anyOf" in sub) and "/not" not in p]
    if sid == engines.C4_SCHEMA_ID:
        assert found == C4_DISJUNCTIONS
        for p, sub in _subschemas(doc):
            if p in found:
                keyword = "oneOf" if "oneOf" in sub else "anyOf"
                assert engines.code_of(sub, keyword) == "KHG-I002"
    else:
        assert found == []


def test_code_of_reads_a_code_or_a_keyword_map():
    assert engines.code_of({"x-khg-code": "KHG-C003"}, "type") == "KHG-C003"
    m = {"x-khg-code": {"default": "KHG-C010", "enum": "KHG-C002"}}
    assert engines.code_of(m, "enum") == "KHG-C002" and engines.code_of(m, "type") == "KHG-C010"
    assert engines.code_of({"x-khg-code": {"enum": "KHG-C002"}}, "type") is None
    assert engines.code_of({"type": "string"}, "type") is None and engines.code_of(True, "type") is None


@pytest.mark.parametrize(("keyword", "path", "code"), [
    ("required", [], "KHG-H001"),
    ("additionalProperties", [], "KHG-H002"),
    ("unevaluatedProperties", [], "KHG-H002"),
    ("additionalProperties", ["incidences", 3], "KHG-H003"),
    ("additionalProperties", ["metadata", "x"], "KHG-H009"),
    ("type", ["incidences", 3, "attrs"], "KHG-H004"),
    ("type", ["metadata"], "KHG-H004"),
    ("enum", ["incidences", 3, "direction"], "KHG-H005"),
    ("required", ["incidences", 3], "KHG-H006"),
    ("type", ["nodes", 0, "node"], "KHG-H007"),
    ("type", ["edges", 1, "edge"], "KHG-H007"),
    ("enum", ["network-type"], "KHG-H008"),
    ("type", ["incidences"], "KHG-H009"),
    ("type", ["nodes", 0, "weight"], "KHG-H009"),
    ("minimum", ["x"], "KHG-H009"),
])
def test_the_h_table(keyword, path, code):
    assert engines.h_code(keyword, path) == code


@pytest.mark.parametrize("engine", ENGINES)
def test_the_vendored_schema_is_coded_by_the_h_table(engine):
    hif = data.load_json("fixture/fixture.hif.json")
    assert engines.findings(engines.HIF_SCHEMA_ID, hif, engine=engine) == []
    bad = copy.deepcopy(hif)
    bad["incidences"][0]["direction"] = "treatment"
    found = engines.findings(engines.HIF_SCHEMA_ID, bad, engine=engine)
    assert [(f["code"], f["path"]) for f in found] == [("KHG-H005", "/incidences/0/direction")]
    assert engines.findings(engines.HIF_SCHEMA_ID, {"nodes": []}, engine=engine)[0]["code"] == "KHG-H001"


@pytest.mark.parametrize("engine", ENGINES)
def test_findings_carry_the_annotated_code_and_the_path(engine):
    record = {"kind": "hyperedge", "id": "f:x", "relation": "r", "status": "believed", "rank": "normal",
              "visibility": "visible", "bindings": [{"bid": "b1", "role": "a", "value": {"entity": "ex:a"}}]}
    found = engines.findings(engines.RECORD_SCHEMA_ID, record, fragment="/definitions/record", engine=engine,
                             path="/records/7")
    assert [(f["code"], f["path"], f["layer"], f["severity"]) for f in found] == \
        [("KHG-C002", "/records/7/status", "C", "error")]


def test_jsonschema_reports_every_violation_and_fastjsonschema_the_first():
    record = {"kind": "hyperedge", "id": "f x", "relation": "r", "status": "believed",
              "bindings": [{"bid": "b1", "role": "a", "value": {"entity": "ex:a"}}], "arity": 2}
    full = engines.findings(engines.RECORD_SCHEMA_ID, record, fragment="/definitions/hyperedge")
    fast = engines.findings(engines.RECORD_SCHEMA_ID, record, fragment="/definitions/hyperedge",
                            engine="fastjsonschema")
    assert {f["code"] for f in full} == {"KHG-C002", "KHG-C009", "KHG-C011"}
    assert len(fast) == 1 and fast[0]["code"] in {f["code"] for f in full}


@pytest.mark.parametrize("engine", ENGINES)
def test_the_engines_never_change_the_instance_or_the_packaged_schemas(engine):
    fixture = data.load_json("fixture/fixture.c1.json")
    before = copy.deepcopy(fixture)
    for sid in ROOTS:
        engines.compile_schema(sid, engine=engine)(fixture)
    assert fixture == before
    assert dict(engines._documents()) == data.schema_documents()


def test_long_messages_are_cut():
    found = engines.findings(engines.RECORD_SCHEMA_ID, {"header": ["x" * 500], "records": []})
    assert found and all(len(f["message"]) <= engines.MESSAGE_LIMIT for f in found)


def test_pointer_escapes_per_rfc_6901():
    assert engines.pointer(["records", 3, "extensions", "a/b~c"]) == "/records/3/extensions/a~1b~0c"
    assert engines.pointer([]) == ""


def test_an_unknown_engine_is_a_value_error():
    with pytest.raises(ValueError):
        engines.check_engine("ajv")
    with pytest.raises(ValueError):
        engines.compile_schema(engines.RECORD_SCHEMA_ID, engine="ajv")
