"""Prototype migration of the KB's pre-contract sample (call it v0) to khg-record/1.0.0, then the gate chain."""
import copy, json, sys, socket, warnings
from pathlib import Path
warnings.filterwarnings("ignore")
HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
class _NoNet(socket.socket):
    def connect(self, *a, **k): raise OSError("network disabled")
socket.socket = _NoNet
import jsonschema
from referencing import Registry, Resource
from khg_proto import Schema, c1_to_hif, hif_to_c1, canonical_doc, cjson, derived, strict_loads
from khg_semantic import validate_document
import role_loaders_sketch as sk

src = strict_loads(open("/home/user/knowledge-Hyper-Graphs-/schemas/sample.hif.json").read())
report = []
# 1. generated schema: one relation per attrs.relation, one role usage per observed role, direction if consistent
rels = {}
for i in src["incidences"]:
    rel = next(e for e in src["edges"] if e["edge"] == i["edge"])["attrs"]["relation"]
    rels.setdefault(rel, {}).setdefault(i["attrs"]["role"], set()).add(i.get("direction"))
types = sorted({n["attrs"]["type"] for n in src["nodes"]})
schema = {"khg_schema": "khg-schema/1.0.0", "id": "kb-sample", "version": "1.0.0",
          "label": "generated by migrate v0 -> khg-record/1.0.0 from schemas/sample.hif.json",
          "entity_types": [{"id": t} for t in types], "roles": [], "relations": []}
role_ids = set()
for rel, roles in sorted(rels.items()):
    counts = {}
    for i in src["incidences"]:
        e = next(x for x in src["edges"] if x["edge"] == i["edge"])
        if e["attrs"]["relation"] == rel:
            counts.setdefault((i["edge"], i["attrs"]["role"]), 0)
            counts[(i["edge"], i["attrs"]["role"])] += 1
    usages = []
    for role, dirs in sorted(roles.items()):
        mx = max(v for (edge, r), v in counts.items() if r == role)
        u = {"role": role, "slot": "core", "fillers": [{"entity": []}], "min": 1, "max": None if mx > 1 else 1}
        if len(dirs) == 1 and None not in dirs:
            u["direction"] = dirs.pop()
        usages.append(u); role_ids.add(role)
    r = {"id": rel, "roles": usages}
    if any("valid-from" in e["attrs"] for e in src["edges"] if e["attrs"]["relation"] == rel):
        r["roles"].append({"role": "start_time", "slot": "time", "fillers": [{"literal": "time"}], "min": 0, "max": 1, "direction": "tail"})
        r["time"] = {"model": "interval", "start": "start_time", "end": "end_time"}
        r["roles"].append({"role": "end_time", "slot": "time", "fillers": [{"literal": "time"}], "min": 0, "max": 1, "direction": "tail"})
        role_ids |= {"start_time", "end_time"}
        report.append(f"MIGRATE-W01 {rel}: edges.attrs.valid-from mapped to a start_time binding (time slot); direction 'tail' chosen by the migration, following the sample's own convention")
    schema["relations"].append(r)
schema["roles"] = [{"id": x} for x in sorted(role_ids)]
S = Schema(schema)
# 2. records
recs = [{"kind": "entity", "id": n["node"], "types": [n["attrs"]["type"]], "label": n["attrs"]["label"]} for n in src["nodes"]]
for e in src["edges"]:
    a = e["attrs"]
    bs = [{"role": i["attrs"]["role"], "value": {"entity": i["node"]}} for i in src["incidences"] if i["edge"] == e["edge"]]
    if "valid-from" in a:
        y, m, d = a["valid-from"].split("-")
        bs.append({"role": "start_time", "value": {"literal": {"datatype": "time", "time": f"+{y}-{m}-{d}T00:00:00Z", "precision": 11}}})
    bs.sort(key=lambda b: (b["role"], cjson(b["value"])))
    for k, b in enumerate(bs, 1):
        b["bid"] = f"b{k}"
    r = {"kind": "fact", "id": e["edge"], "relation": a["relation"], "status": "asserted", "bindings": bs,
         "evidence": [{"id": "e1", "type": "imported", "mode": "automatic", "source": {"doc_id": a["source"]}}]}
    if "weight" in e:
        r["extensions"] = {"hif:weight": e["weight"]}
        report.append(f"MIGRATE-W02 {e['edge']}: HIF weight {e['weight']} kept as extensions.hif:weight; not read as confidence (no scale is stated)")
    if a.get("arity") is not None and derived(S, r)["arity"] != a["arity"]:
        report.append(f"MIGRATE-E01 {e['edge']}: stored arity {a['arity']} != derived {derived(S, r)['arity']}")
    recs.append(r)
doc = {"header": {"kind": "header", "khg": "khg-record/1.0.0", "document_id": "kb-sample-migrated",
                  "schema": {"id": "kb-sample", "version": "1.0.0", "sha256": S.sha256()}, "snapshot": "current", "complete": True,
                  "extensions": {"hif:metadata": {k: v for k, v in src["metadata"].items() if k not in ("conventions", "schema")}}},
       "records": recs}
report.append("MIGRATE-I01 metadata.conventions and metadata.schema (moving 'main' URL) replaced by the khg-hif/1.0.0 declaration block")
report.append("MIGRATE-I02 edges.attrs.arity dropped: arity is derived; stored values checked against the derived ones")
HIF = json.loads((HERE / "hif_schema_v0.1.0.json").read_text())
REC = json.loads((HERE / "khg-record-1.0.0.schema.json").read_text())
PROF = json.loads((HERE / "khg-hif-1.0.0.schema.json").read_text())
LANG = json.loads((HERE / "khg-schema-1.0.0.schema.json").read_text())
reg = Registry().with_resource(HIF["$id"], Resource.from_contents(HIF))
chk = lambda s, x: [e.message[:100] for e in jsonschema.Draft7Validator(s, registry=reg).iter_errors(x)]
print("generated schema vs khg-schema/1.0.0:", chk(LANG, schema) or "OK")
print("migrated C1 vs khg-record/1.0.0:", chk(REC, doc) or "OK")
print("semantic findings:", validate_document(doc, S) or "none")
hif = c1_to_hif(doc, S)
print("HIF vs vendored schema:", chk(HIF, hif) or "OK", "| vs profile:", chk(PROF, hif) or "OK", "| network-type:", hif["network-type"])
H, c = sk.to_xgi(copy.deepcopy(hif)); G, c2 = sk.to_hnx(sk.from_xgi(H, c)); back = hif_to_c1(sk.from_hnx(G, c2), S)
print("chain C1->HIF->XGI->HIF->HNX->HIF->C1 canonical equality:", cjson(canonical_doc(back, S)) == cjson(canonical_doc(doc, S)))
print("roles kept:", sorted((i["edge"], i["attrs"]["role"]) for i in hif["incidences"]) == sorted((i["edge"], i["attrs"]["role"]) for i in src["incidences"]) + [("f1", "start_time")] or "compare")
print("\n".join(report))
json.dump(schema, open(HERE / "kb-sample.schema.json", "w"), indent=1, ensure_ascii=False)
json.dump(doc, open(HERE / "kb-sample-migrated.khg.json", "w"), indent=1, ensure_ascii=False)
