#!/usr/bin/env python3
"""Regenerate kb/00-index/map-of-content.md from note front matter."""
from __future__ import annotations

import datetime as dt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KB = ROOT / "kb"
OUT = KB / "00-index" / "map-of-content.md"


def fm(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    data: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" in line and not line.startswith(" "):
            k, _, v = line.partition(":")
            data[k.strip()] = v.strip()
    return data


def first_paragraph(text: str) -> str:
    body = text
    if body.startswith("---\n"):
        end = body.find("\n---", 4)
        body = body[end + 4:]
    for para in body.split("\n\n"):
        p = para.strip()
        if p and not p.startswith("#") and not p.startswith("|") and not p.startswith("```") and not p.startswith("-"):
            return " ".join(p.split())[:220]
    return ""


def main() -> None:
    today = dt.date.today().isoformat()
    lines = [
        "---",
        "title: Map of content",
        "type: index",
        "status: reviewed",
        "tags: [index, navigation]",
        "created: 2026-09-19",
        f"updated: {today}",
        "---",
        "",
        "# Map of content",
        "",
        "Generated by `tools/build_index.py`. Every note in `kb/`, grouped by section, with its type and status.",
        "",
    ]
    total = 0
    for section in sorted(p for p in KB.iterdir() if p.is_dir()):
        notes = sorted(p for p in section.glob("*.md") if p.name != "README.md")
        readme = section / "README.md"
        title = section.name
        if readme.exists():
            t = fm(readme.read_text(encoding="utf-8")).get("title")
            if t:
                title = t
        lines.append(f"## {section.name} — {title}" if title != section.name else f"## {section.name}")
        lines.append("")
        if readme.exists():
            lines.append(f"Section overview: [{section.name}/README.md](../{section.name}/README.md)")
            lines.append("")
        if notes:
            lines.append("| Note | Type | Status | Summary |")
            lines.append("|---|---|---|---|")
        for n in notes:
            text = n.read_text(encoding="utf-8", errors="replace")
            meta = fm(text)
            total += 1
            summary = first_paragraph(text).replace("|", "\\|")
            lines.append(
                f"| [{meta.get('title', n.stem)}](../{section.name}/{n.name}) | {meta.get('type', '')} | {meta.get('status', '')} | {summary} |"
            )
        lines.append("")
    lines.append(f"_{total} notes indexed on {today}._")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({total} notes)")


if __name__ == "__main__":
    main()
